console:
  max_message_size_bytes: 409600
logger:
  level: "INFO"
runtime:
  js_entrypoint: "build/index.js"
session:
  token_expiry_sec: 7200
socket:
  server_key: "tictactoe_server_key"
  max_message_size_bytes: 4096
  max_request_size_bytes: 131072
  cors_allow_origins:
    - "*"
